# Generated by Django 5.0.2 on 2025-07-27 23:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_alter_clientprofile_email_alter_clientprofile_nom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ligne', models.CharField(choices=[('prestation', 'Prestation'), ('frais', 'Frais')], max_length=200)),
                ('type_frais', models.CharField(blank=True, choices=[('standard', 'Standard'), ('forfait', 'Forfait'), ('offert', 'Offert')], max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ligne de contrat',
                'verbose_name_plural': 'Lignes de contrat',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneContratIntervenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps_intervenant', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('taux_horaire', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('montant_intervenant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Intervenant ligne contrat',
                'verbose_name_plural': 'Intervenants lignes contrat',
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=50, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('actif', 'Actif'), ('termine', 'Terminé'), ('annule', 'Annulé'), ('suspendu', 'Suspendu')], default='brouillon', max_length=20)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('appliquer_tva', models.BooleanField(default=True, verbose_name='Appliquer la TVA')),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('conditions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('contenu_personnalise', models.TextField(blank=True, verbose_name='Contenu personnalisé du contrat')),
                ('variables_personnalisees', models.JSONField(default=dict, verbose_name='Variables personnalisées')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='users.clientprofile')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-date_creation'],
            },
        ),
    ]
