# Generated by Django 5.0.2 on 2025-07-28 03:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('devis', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=50, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('actif', 'Actif'), ('termine', 'Terminé'), ('annule', 'Annulé'), ('suspendu', 'Suspendu')], default='brouillon', max_length=20)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('appliquer_tva', models.BooleanField(default=True, verbose_name='Appliquer la TVA')),
                ('taux_frais_agence', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('appliquer_frais_agence', models.BooleanField(default=False, verbose_name="Appliquer les frais d'agence")),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_frais_agence', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('conditions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('contenu_personnalise', models.TextField(blank=True, verbose_name='Contenu personnalisé du contrat')),
                ('variables_personnalisees', models.JSONField(default=dict, verbose_name='Variables personnalisées')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='users.clientprofile')),
                ('devis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrat', to='devis.devis')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ligne', models.CharField(choices=[('prestation', 'Prestation'), ('frais', 'Frais')], max_length=200)),
                ('type_frais', models.CharField(blank=True, choices=[('standard', 'Standard'), ('forfait', 'Forfait'), ('offert', 'Offert')], max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes_contrat', to='catalog.activity')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='contrats.contrat')),
                ('frais_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes_contrat', to='catalog.fraiscategory')),
                ('ligne_frais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes_contrat', to='catalog.lignefrais')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes_contrat', to='catalog.service')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_contrat', to='catalog.unitestandard')),
            ],
            options={
                'verbose_name': 'Ligne de contrat',
                'verbose_name_plural': 'Lignes de contrat',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EcheancierContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_echeance', models.CharField(choices=[('acompte', 'Acompte'), ('tranche', 'Tranche de paiement'), ('solde', 'Solde'), ('retention', 'Retenue de garantie')], max_length=20)),
                ('numero_echeance', models.PositiveIntegerField(help_text="Numéro de l'échéance (1, 2, 3, etc.)")),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('pourcentage', models.DecimalField(decimal_places=2, help_text='Pourcentage du montant total', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_echeance', models.DateField()),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('en_retard', 'En retard'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('alerte_envoyee', models.BooleanField(default=False, help_text="Alerte envoyée 3 jours avant l'échéance")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='contrats.contrat')),
            ],
            options={
                'verbose_name': 'Échéance de contrat',
                'verbose_name_plural': 'Échéances de contrat',
                'ordering': ['contrat', 'numero_echeance'],
                'unique_together': {('contrat', 'numero_echeance')},
            },
        ),
        migrations.CreateModel(
            name='LigneContratIntervenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps_intervenant', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('taux_horaire', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('montant_intervenant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ligne_contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervenants', to='contrats.lignecontrat')),
                ('profile_intervenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_contrat', to='catalog.intervenantprofile')),
            ],
            options={
                'verbose_name': 'Intervenant ligne contrat',
                'verbose_name_plural': 'Intervenants lignes contrat',
                'unique_together': {('ligne_contrat', 'profile_intervenant')},
            },
        ),
    ]
