# Generated by Django 5.0.2 on 2025-07-27 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_alter_tauxhoraire_taux_heure'),
        ('contrats', '0001_initial'),
        ('devis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='devis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrat', to='devis.devis'),
        ),
        migrations.AddField(
            model_name='lignecontrat',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes_contrat', to='catalog.activity'),
        ),
        migrations.AddField(
            model_name='lignecontrat',
            name='contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='contrats.contrat'),
        ),
        migrations.AddField(
            model_name='lignecontrat',
            name='frais_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes_contrat', to='catalog.fraiscategory'),
        ),
        migrations.AddField(
            model_name='lignecontrat',
            name='ligne_frais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes_contrat', to='catalog.lignefrais'),
        ),
        migrations.AddField(
            model_name='lignecontrat',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes_contrat', to='catalog.service'),
        ),
        migrations.AddField(
            model_name='lignecontrat',
            name='unite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_contrat', to='catalog.unitestandard'),
        ),
        migrations.AddField(
            model_name='lignecontratintervenant',
            name='ligne_contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervenants', to='contrats.lignecontrat'),
        ),
        migrations.AddField(
            model_name='lignecontratintervenant',
            name='profile_intervenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_contrat', to='catalog.intervenantprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='lignecontratintervenant',
            unique_together={('ligne_contrat', 'profile_intervenant')},
        ),
    ]
