# Generated by Django 5.0.2 on 2025-07-25 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du template')),
                ('type_template', models.CharField(choices=[('prestation', 'Prestation de services'), ('maintenance', 'Maintenance'), ('formation', 'Formation'), ('conseil', 'Conseil'), ('personnalise', 'Personnalisé')], default='prestation', max_length=20)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('contenu', models.TextField(verbose_name='Contenu du template')),
                ('variables_defaut', models.JSONField(default=dict, verbose_name='Variables par défaut')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Template actif')),
                ('est_public', models.BooleanField(default=True, verbose_name='Template public')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_contrat_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template de contrat',
                'verbose_name_plural': 'Templates de contrat',
                'ordering': ['nom'],
            },
        ),
    ]
