# Generated by Django 5.0.2 on 2025-07-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='echeances_contrat',
            field=models.JSONField(default=list, verbose_name='Configuration des échéances de paiement'),
        ),
    ]
