# Generated by Django 5.0.2 on 2025-07-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='contenu_personnalise',
            field=models.TextField(blank=True, verbose_name='Contenu personnalisé du contrat'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='variables_personnalisees',
            field=models.JSONField(default=dict, verbose_name='Variables personnalisées'),
        ),
    ]
