# Generated by Django 5.0.2 on 2025-07-27 23:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='appliquer_frais_agence',
            field=models.BooleanField(default=False, verbose_name="Appliquer les frais d'agence"),
        ),
        migrations.AddField(
            model_name='contrat',
            name='montant_frais_agence',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contrat',
            name='taux_frais_agence',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
