# Generated by Django 5.0.2 on 2025-07-28 00:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0003_contrat_contenu_personnalise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcheancierContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_echeance', models.CharField(choices=[('acompte', 'Acompte'), ('tranche', 'Tranche de paiement'), ('solde', 'Solde'), ('retention', 'Retenue de garantie')], max_length=20)),
                ('numero_echeance', models.PositiveIntegerField(help_text="Numéro de l'échéance (1, 2, 3, etc.)")),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('pourcentage', models.DecimalField(decimal_places=2, help_text='Pourcentage du montant total', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_echeance', models.DateField()),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('en_retard', 'En retard'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('alerte_envoyee', models.BooleanField(default=False, help_text="Alerte envoyée 3 jours avant l'échéance")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='contrats.contrat')),
            ],
            options={
                'verbose_name': 'Échéance de contrat',
                'verbose_name_plural': 'Échéances de contrat',
                'ordering': ['contrat', 'numero_echeance'],
                'unique_together': {('contrat', 'numero_echeance')},
            },
        ),
    ]
