# Generated by Django 5.0.2 on 2025-07-30 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0003_contrat_fichier_signe_alter_contrat_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('actif', 'Actif'), ('termine', 'Terminé'), ('annule', 'Annulé'), ('suspendu', 'Suspendu'), ('archive', 'Archivé'), ('envoye', 'Envoyé'), ('signe', 'Signé'), ('cloture', 'Cloturé')], default='brouillon', max_length=20),
        ),
        migrations.CreateModel(
            name='Avenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=50, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_signature', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('signe', 'Signé'), ('annule', 'Annulé')], default='brouillon', max_length=20)),
                ('intitule_avenant', models.CharField(max_length=200, verbose_name="Intitulé de l'avenant")),
                ('objet_avenant', models.TextField(verbose_name="Objet de l'avenant")),
                ('type_modification', models.CharField(choices=[('modifier', 'Modifier'), ('completer', 'Compléter'), ('preciser', 'Préciser'), ('prolonger', 'Prolonger'), ('reduire', 'Réduire'), ('annuler', 'Annuler')], default='modifier', max_length=50)),
                ('modifications', models.JSONField(default=list, help_text='Liste des clauses modifiées avec ancienne et nouvelle version', verbose_name='Liste des modifications')),
                ('contenu_personnalise', models.TextField(blank=True, verbose_name="Contenu personnalisé de l'avenant")),
                ('variables_personnalisees', models.JSONField(default=dict, verbose_name='Variables personnalisées')),
                ('fichier_signe', models.FileField(blank=True, null=True, upload_to='avenants/signes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avenants', to='contrats.contrat')),
            ],
            options={
                'verbose_name': 'Avenant',
                'verbose_name_plural': 'Avenants',
                'ordering': ['-date_creation'],
            },
        ),
    ]
