# Generated by Django 5.0.2 on 2025-12-10 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0006_alter_contrat_devis'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratHistoriqueMontant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('type_modification', models.CharField(choices=[('ajout_devis', 'Ajout de devis'), ('suppression_devis', 'Suppression de devis'), ('modification_ligne', 'Modification de ligne'), ('avenant', 'Avenant'), ('recalcul', 'Recalcul')], max_length=50)),
                ('montant_ht_avant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant HT avant')),
                ('montant_tva_avant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant TVA avant')),
                ('montant_ttc_avant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant TTC avant')),
                ('montant_ht_apres', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant HT après')),
                ('montant_tva_apres', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant TVA après')),
                ('montant_ttc_apres', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant TTC après')),
                ('description', models.TextField(blank=True, verbose_name='Description de la modification')),
                ('metadata', models.JSONField(default=dict, verbose_name='Métadonnées supplémentaires')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_montants', to='contrats.contrat')),
            ],
            options={
                'verbose_name': 'Historique de montant de contrat',
                'verbose_name_plural': 'Historiques de montants de contrats',
                'ordering': ['-date_modification'],
            },
        ),
    ]
