# Generated by Django 5.0.2 on 2025-12-11 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0002_alter_facture_echeance'),
        ('contrats', '0009_refactor_echeancier_architecture'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ligneecheanciercontrat',
            unique_together={('echeancier', 'numero_echeance')},
        ),
        migrations.DeleteModel(
            name='EcheancierContratOld',
        ),
    ]
