# Generated by Django 5.0.2 on 2025-12-12 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0010_alter_ligneecheanciercontrat_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echeanciercontrat',
            name='contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='contrats.contrat'),
        ),
    ]
