# Generated by Django 5.0.2 on 2025-12-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0011_alter_echeanciercontrat_contrat'),
    ]

    operations = [
        migrations.AddField(
            model_name='echeanciercontrat',
            name='echeances_contrat',
            field=models.JSONField(default=list, verbose_name='Configuration des échéances de paiement'),
        ),
    ]
