# Generated by Django 5.0.2 on 2025-07-28 03:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=50, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validite', models.DateField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('expire', 'Expiré')], default='brouillon', max_length=20)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('appliquer_tva', models.BooleanField(default=True, verbose_name='Appliquer la TVA')),
                ('taux_frais_agence', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('appliquer_frais_agence', models.BooleanField(default=False, verbose_name="Appliquer les frais d'agence")),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_frais_agence', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('conditions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='users.clientprofile')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ligne', models.CharField(choices=[('prestation', 'Prestation'), ('frais', 'Frais')], max_length=200)),
                ('type_frais', models.CharField(blank=True, choices=[('standard', 'Standard'), ('forfait', 'Forfait'), ('offert', 'Offert')], max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes_devis', to='catalog.activity')),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='devis.devis')),
                ('frais_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes_devis', to='catalog.fraiscategory')),
                ('ligne_frais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes_devis', to='catalog.lignefrais')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes_devis', to='catalog.service')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_devis', to='catalog.unitestandard')),
            ],
            options={
                'verbose_name': 'Ligne de devis',
                'verbose_name_plural': 'Lignes de devis',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevisEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('email_destinataire', models.EmailField(max_length=254)),
                ('sujet', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('statut_envoi', models.CharField(choices=[('envoye', 'Envoyé'), ('erreur', 'Erreur'), ('en_cours', 'En cours')], default='en_cours', max_length=20)),
                ('erreur_message', models.TextField(blank=True, null=True)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_envoyes', to='devis.devis')),
            ],
            options={
                'verbose_name': 'Email de devis',
                'verbose_name_plural': 'Emails de devis',
                'ordering': ['-date_envoi'],
                'unique_together': {('devis', 'version')},
            },
        ),
        migrations.CreateModel(
            name='LigneDevisIntervenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps_intervenant', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('taux_horaire', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('montant_intervenant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ligne_devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervenants', to='devis.lignedevis')),
                ('profile_intervenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_devis', to='catalog.intervenantprofile')),
            ],
            options={
                'verbose_name': 'Intervenant ligne devis',
                'verbose_name_plural': 'Intervenants lignes devis',
                'unique_together': {('ligne_devis', 'profile_intervenant')},
            },
        ),
    ]
