# Generated by Django 5.0.2 on 2025-10-01 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('devis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignedevis',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes_devis_activities', to='catalog.activity'),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes_devis_services', to='catalog.service'),
        ),
    ]
