# Generated by Django 5.0.2 on 2025-07-21 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='appliquer_tva',
            field=models.BooleanField(default=True, verbose_name='Appliquer la TVA'),
        ),
        migrations.AddField(
            model_name='devis',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
