# Generated by Django 5.0.2 on 2025-07-22 13:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_tauxhoraire_taux_heure'),
        ('devis', '0002_devis_appliquer_tva_devis_taux_tva'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedevis',
            name='frais_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes_devis', to='catalog.fraiscategory'),
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='ligne_frais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes_devis', to='catalog.lignefrais'),
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='type_ligne',
            field=models.CharField(choices=[('prestation', 'Prestation'), ('frais', 'Frais')], default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes_devis', to='catalog.activity'),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes_devis', to='catalog.service'),
        ),
    ]
