# Generated by Django 5.0.2 on 2025-07-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0003_lignedevis_frais_category_lignedevis_ligne_frais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedevis',
            name='type_frais',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('forfait', 'Forfait'), ('offert', 'Offert')], max_length=200, null=True),
        ),
    ]
