# Generated by Django 5.0.2 on 2025-07-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0004_lignedevis_type_frais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignedevis',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
