# Generated by Django 5.0.2 on 2026-01-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0004_alter_lignedevis_unite'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedevis',
            name='commentaire_retrait',
            field=models.TextField(blank=True, default='', help_text='Raison du retrait de la ligne'),
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='date_retrait',
            field=models.DateTimeField(blank=True, help_text='Date à laquelle la ligne a été retirée', null=True),
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='statut',
            field=models.CharField(choices=[('active', 'Active'), ('retiree', 'Retirée')], default='active', max_length=20),
        ),
    ]
