# Generated by Django 5.0.2 on 2025-07-24 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0005_alter_lignedevis_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevisEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('email_destinataire', models.EmailField(max_length=254)),
                ('sujet', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('statut_envoi', models.CharField(choices=[('envoye', 'Envoyé'), ('erreur', 'Erreur'), ('en_cours', 'En cours')], default='en_cours', max_length=20)),
                ('erreur_message', models.TextField(blank=True, null=True)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_envoyes', to='devis.devis')),
            ],
            options={
                'verbose_name': 'Email de devis',
                'verbose_name_plural': 'Emails de devis',
                'ordering': ['-date_envoi'],
                'unique_together': {('devis', 'version')},
            },
        ),
    ]
