# Generated by Django 5.0.2 on 2025-07-20 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'activité")),
                ('duree_standard', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Durée standard (heures)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IntervenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du profil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Profil intervenant',
                'verbose_name_plural': 'Profils intervenant',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps_intervenant', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temps intervenant (heures)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.activity', verbose_name='Activité')),
                ('profile_intervenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.intervenantprofile', verbose_name='Profil intervenant')),
            ],
            options={
                'verbose_name': "Profil d'activité",
                'verbose_name_plural': "Profils d'activité",
                'unique_together': {('activity', 'profile_intervenant')},
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='profiles_intervenant',
            field=models.ManyToManyField(related_name='activities', through='catalog.ActivityProfile', to='catalog.intervenantprofile', verbose_name='Profils intervenant'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la prestation')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='catalog.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Prestation',
                'verbose_name_plural': 'Prestations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='catalog.service', verbose_name='Prestation'),
        ),
        migrations.CreateModel(
            name='TauxHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_intervenant', models.CharField(choices=[('intermediaire', 'Intermédiaire'), ('operationnel', 'Opérationnel'), ('senior', 'Senior')], max_length=20, verbose_name='Niveau intervenant')),
                ('taux_heure', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Taux horaire (€)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taux_horaires', to='catalog.activity', verbose_name='Activité')),
                ('profile_intervenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taux_horaires', to='catalog.intervenantprofile', verbose_name='Profil intervenant')),
            ],
            options={
                'verbose_name': 'Taux horaire',
                'verbose_name_plural': 'Taux horaires',
                'ordering': ['-created_at'],
                'unique_together': {('niveau_intervenant', 'activity', 'profile_intervenant')},
            },
        ),
    ]
