# Generated by Django 5.0.2 on 2025-07-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée (minutes)'),
        ),
    ]
