# Generated by Django 5.0.2 on 2025-11-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='duree_standard',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Durée standard (heures)'),
        ),
    ]
