# Generated by Django 5.0.2 on 2025-07-21 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_unitestandard'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraisCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie de frais',
                'verbose_name_plural': 'Catégories de frais',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LigneFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_frais', models.CharField(choices=[('rh', 'Budget RH mobilisé'), ('technique', 'Frais techniques et matériels'), ('sous_traitance', 'Sous-traitance / prestataires externes'), ('deplacement', 'Déplacements et logistique'), ('administratif', 'Frais administratifs et annexes'), ('marge', 'Marge commerciale et ajustements'), ('taxes', 'Taxes et TVA')], max_length=20, verbose_name='Type de frais')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_frais', to='catalog.fraiscategory', verbose_name='Catégorie de frais')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_frais', to='projects.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Ligne de frais',
                'verbose_name_plural': 'Lignes de frais',
                'ordering': ['-created_at'],
            },
        ),
    ]
