# Generated by Django 5.0.2 on 2025-07-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_service_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Durée (heures)'),
        ),
    ]
