# Generated by Django 5.0.2 on 2025-07-12 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_service_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du profil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Profil intervenant',
                'verbose_name_plural': 'Profils intervenant',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='profile_intervenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='catalog.intervenantprofile', verbose_name='Profil intervenant'),
        ),
    ]
