# Generated by Django 5.0.2 on 2025-07-21 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_fraiscategory_lignefrais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignefrais',
            name='project',
        ),
    ]
