# Generated by Django 5.0.2 on 2025-07-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_lignefrais_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tauxhoraire',
            name='taux_heure',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Taux horaire (GNF)'),
        ),
    ]
