# Generated by Django 5.0.2 on 2026-01-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('project_member', 'Membre de projet'), ('task_assignment', 'Attribution de tâche'), ('task_update', 'Mise à jour de tâche'), ('event_created', 'Événement créé'), ('event_update', "Mise à jour d'événement"), ('document_shared', 'Document partagé'), ('team_update', "Mise à jour d'équipe"), ('message', 'Nouveau message')], max_length=50),
        ),
    ]
