# Generated by Django 5.0.2 on 2025-08-01 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0001_initial'),
        ('projects', '0004_remove_projecttask_phase_delete_projectphase'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='ligne_devis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_devis', to='devis.lignedevis'),
        ),
    ]
