# Generated by Django 5.0.2 on 2025-12-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_timesheet_validation_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcomment',
            name='attachments',
            field=models.JSONField(blank=True, default=list, help_text='Liste des pièces jointes (nom, url, type, taille)'),
        ),
    ]
