version: "3.8"

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: project_saas_db
      POSTGRES_USER: project_saas_user
      POSTGRES_PASSWORD: project_saas_password
    networks:
      - project_saas_network

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - project_saas_network

  backend:
    build: ./backend
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      DEBUG: "True"
      DB_NAME: project_saas_db
      DB_USER: project_saas_user
      DB_PASSWORD: project_saas_password
      DB_HOST: db
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379/0
      ALLOWED_HOSTS: "*"
    depends_on:
      - db
      - redis
    networks:
      - project_saas_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
    depends_on:
      - backend
    networks:
      - project_saas_network

  mailpit:
    image: axllent/mailpit
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - project_saas_network

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:

networks:
  project_saas_network:
    driver: bridge
