# Generated by Django 5.0.2 on 2025-06-21 19:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('objectives', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('Événementiel', 'Événementiel'), ('Communication', 'Communication'), ('Audiovisuel', 'Audiovisuel'), ('Production', 'Production'), ('Digital', 'Digital'), ('Conseil', 'Conseil')], max_length=20)),
                ('category', models.CharField(blank=True, choices=[('Corporate', 'Corporate'), ('Marketing', 'Marketing'), ('Institutionnel', 'Institutionnel'), ('Commercial', 'Commercial'), ('Interne', 'Interne')], max_length=20)),
                ('status', models.CharField(choices=[('Planification', 'Planification'), ('En cours', 'En cours'), ('Production', 'Production'), ('En pause', 'En pause'), ('Terminé', 'Terminé')], default='Planification', max_length=20)),
                ('priority', models.CharField(choices=[('Basse', 'Basse'), ('Normale', 'Normale'), ('Haute', 'Haute'), ('Urgente', 'Urgente')], default='Normale', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client', models.CharField(max_length=200)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('personnel', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('marketing', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_details', to='projects.project')),
            ],
            options={
                'verbose_name': 'Détail du budget',
                'verbose_name_plural': 'Détails du budget',
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Chef de projet', 'Chef de projet'), ('Designer', 'Designer'), ('Développeur', 'Développeur'), ('Rédacteur', 'Rédacteur'), ('Consultant', 'Consultant'), ('Assistant', 'Assistant')], max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_members', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre du projet',
                'verbose_name_plural': 'Membres du projet',
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(related_name='projects', through='projects.ProjectMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('À faire', 'À faire'), ('En cours', 'En cours'), ('Terminé', 'Terminé'), ('En pause', 'En pause')], default='À faire', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'ordering': ['due_date', 'created_at'],
            },
        ),
    ]
