# Generated by Django 5.0.2 on 2025-07-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttask',
            options={'ordering': ['start_date', 'due_date', 'created_at'], 'verbose_name': 'Tâche', 'verbose_name_plural': 'Tâches'},
        ),
        migrations.AddField(
            model_name='projecttask',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
