# Generated by Django 5.0.2 on 2025-08-01 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0006_alter_contrat_devis'),
        ('projects', '0002_alter_project_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='Contrat associé au projet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='contrats.contrat'),
        ),
    ]
