# Generated by Django 5.0.2 on 2025-08-01 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttask',
            name='phase',
        ),
        migrations.DeleteModel(
            name='ProjectPhase',
        ),
    ]
