# Generated by Django 5.0.2 on 2025-07-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
