# Generated by Django 5.0.2 on 2025-08-02 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0001_initial'),
        ('projects', '0005_projecttask_ligne_devis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='ligne_devis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_ligne_devis', to='devis.lignedevis'),
        ),
    ]
