# Generated by Django 5.0.2 on 2025-08-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_projecttask_ligne_devis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Prospection', 'Prospection'), ('Production', 'Production'), ('Livraison', 'Livraison'), ('Terminé', 'Terminé')], default='Prospection', max_length=20),
        ),
    ]
