# Generated by Django 5.0.2 on 2025-07-14 17:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_departments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectbudget',
            options={'verbose_name': 'Budget du projet', 'verbose_name_plural': 'Budgets des projets'},
        ),
        migrations.AlterModelOptions(
            name='projectevent',
            options={'ordering': ['start_date'], 'verbose_name': 'Événement du projet', 'verbose_name_plural': 'Événements du projet'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.RemoveField(
            model_name='projectevent',
            name='date',
        ),
        migrations.RemoveField(
            model_name='projectevent',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='projectevent',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='projectevent',
            name='type',
        ),
        migrations.AddField(
            model_name='project',
            name='contract',
            field=models.CharField(blank=True, help_text='Référence du contrat ou de la mission interne', max_length=100),
        ),
        migrations.AddField(
            model_name='projectevent',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectevent',
            name='event_type',
            field=models.CharField(choices=[('meeting', 'Réunion'), ('deadline', 'Échéance'), ('milestone', 'Jalon'), ('review', 'Revue'), ('other', 'Autre')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='projectevent',
            name='is_all_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectevent',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmember',
            name='allocation_percentage',
            field=models.IntegerField(default=100, help_text='Pourcentage de temps alloué au projet', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='actual_hours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Indique si cette tâche est un modèle'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='template_category',
            field=models.CharField(blank=True, help_text='Catégorie du modèle de tâche', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Prospection', 'Prospection'), ('Devis', 'Devis'), ('Production', 'Production'), ('Livraison', 'Livraison'), ('Terminé', 'Terminé')], default='Prospection', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Externe', 'Externe'), ('Interne', 'Interne')], max_length=20),
        ),
        migrations.AlterField(
            model_name='projectbudget',
            name='marketing',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Budget pour le marketing', max_digits=10),
        ),
        migrations.AlterField(
            model_name='projectbudget',
            name='other',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Autres dépenses', max_digits=10),
        ),
        migrations.AlterField(
            model_name='projectbudget',
            name='personnel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Budget pour le personnel', max_digits=10),
        ),
        migrations.AlterField(
            model_name='projectbudget',
            name='production',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Budget pour la production', max_digits=10),
        ),
        migrations.AlterField(
            model_name='projectevent',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='project_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='projects.project')),
            ],
            options={
                'verbose_name': 'Phase du projet',
                'verbose_name_plural': 'Phases du projet',
                'ordering': ['order', 'start_date'],
            },
        ),
        migrations.AddField(
            model_name='projecttask',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.projectphase'),
        ),
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('description', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='projects.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='projects.projecttask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_timesheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feuille de temps',
                'verbose_name_plural': 'Feuilles de temps',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('user', 'project', 'task', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
