# Generated by Django 5.0.2 on 2025-07-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('projects', '0007_alter_projectbudget_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='departments',
        ),
        migrations.AlterField(
            model_name='projectevent',
            name='event_type',
            field=models.CharField(choices=[('meeting', 'Réunion'), ('deadline', 'Échéance'), ('milestone', 'Jalon'), ('review', 'Revue'), ('other', 'Autre')], max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='departments',
            field=models.ManyToManyField(help_text='Départements impliqués', related_name='projects', to='departments.department'),
        ),
    ]
