# Generated by Django 5.0.2 on 2025-11-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_taskcomment_projectnotification_timesheettimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='validation_comment',
            field=models.TextField(blank=True, help_text='Commentaire du chef de projet lors de la validation'),
        ),
    ]
