# Generated by Django 5.0.2 on 2025-11-27 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('devis', '0002_alter_lignedevis_activity_alter_lignedevis_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignedevis',
            name='unite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes_devis', to='catalog.unitestandard'),
        ),
    ]
