# Generated by Django 5.0.2 on 2025-11-28 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_activity_duree_standard'),
        ('devis', '0003_alter_lignedevis_unite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignedevis',
            name='unite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_devis', to='catalog.unitestandard'),
        ),
    ]
