# Generated by Django 5.0.2 on 2025-12-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_fieldpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldpermission',
            name='permission',
            field=models.CharField(choices=[('read', 'Read'), ('write', 'Write')], max_length=10),
        ),
    ]
