# Generated by Django 5.0.2 on 2025-12-14 16:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0007_alter_fieldpermission_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fieldpermission',
            unique_together={('user', 'content_type', 'field_name', 'permission')},
        ),
    ]
