# Generated by Django 5.0.2 on 2025-08-04 22:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrats', '0006_alter_contrat_devis'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationFacturation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facturation_automatique', models.BooleanField(default=True, verbose_name='Facturation automatique')),
                ('delai_avant_echeance', models.PositiveIntegerField(default=7, verbose_name='Délai avant échéance (jours)')),
                ('relance_automatique', models.BooleanField(default=True, verbose_name='Relances automatiques')),
                ('prefixe_facture', models.CharField(default='FAC', max_length=10, verbose_name='Préfixe facture')),
                ('format_numero', models.CharField(default='FAC{year}{numero:04d}', max_length=50, verbose_name='Format numéro')),
                ('conditions_paiement_defaut', models.TextField(default='Paiement à 30 jours', verbose_name='Conditions de paiement par défaut')),
                ('iban_defaut', models.CharField(blank=True, max_length=50, verbose_name='IBAN par défaut')),
                ('bic_defaut', models.CharField(blank=True, max_length=20, verbose_name='BIC par défaut')),
                ('compte_bancaire_defaut', models.CharField(blank=True, max_length=50, verbose_name='Compte bancaire par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration de facturation',
                'verbose_name_plural': 'Configurations de facturation',
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=50, unique=True)),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('date_echeance', models.DateField()),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('emise', 'Émise'), ('envoyee', 'Envoyée'), ('payee', 'Payée'), ('en_retard', 'En retard'), ('annulee', 'Annulée'), ('partiellement_payee', 'Partiellement payée')], default='brouillon', max_length=20)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_frais_agence', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_restant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('appliquer_tva', models.BooleanField(default=True)),
                ('taux_frais_agence', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('appliquer_frais_agence', models.BooleanField(default=False)),
                ('mode_paiement', models.CharField(choices=[('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('mobile_money', 'Mobile Money')], default='virement', max_length=50)),
                ('iban', models.CharField(blank=True, max_length=50)),
                ('bic', models.CharField(blank=True, max_length=20)),
                ('compte_bancaire', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('conditions_paiement', models.TextField(blank=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='factures/pdf/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='users.clientprofile')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='contrats.contrat')),
                ('echeance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='contrats.echeanciercontrat')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ligne', models.CharField(choices=[('prestation', 'Prestation'), ('frais', 'Frais'), ('acompte', 'Acompte'), ('solde', 'Solde')], max_length=20)),
                ('description', models.TextField()),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='billings.facture')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaiementFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_paiement', models.DateField()),
                ('mode_paiement', models.CharField(choices=[('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('mobile_money', 'Mobile Money')], max_length=50)),
                ('reference_paiement', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='billings.facture')),
            ],
            options={
                'verbose_name': 'Paiement de facture',
                'verbose_name_plural': 'Paiements de factures',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
