# Generated by Django 5.0.2 on 2025-12-11 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0002_alter_facture_echeance'),
        ('contrats', '0010_alter_ligneecheanciercontrat_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='echeance',
        ),
        migrations.AddField(
            model_name='facture',
            name='ligne_echeancier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='contrats.ligneecheanciercontrat'),
        ),
    ]
