# Generated by Django 5.0.2 on 2025-12-11 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0001_initial'),
        ('contrats', '0009_refactor_echeancier_architecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='echeance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='contrats.echeanciercontrat'),
        ),
    ]
