# Generated by Django 5.0.2 on 2025-08-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=255, unique=True)),
                ('cache_data', models.JSONField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['cache_key'], name='dashboard_d_cache_k_80159c_idx'), models.Index(fields=['expires_at'], name='dashboard_d_expires_d6f0f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='DashboardMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('overview', "Vue d'ensemble"), ('projects', 'Projets'), ('financial', 'Financier'), ('performance', 'Performance'), ('calendar', 'Calendrier')], max_length=20)),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.JSONField()),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['metric_type', 'period_start'], name='dashboard_d_metric__fc5518_idx'), models.Index(fields=['calculated_at'], name='dashboard_d_calcula_77be04_idx')],
                'unique_together': {('metric_type', 'metric_name', 'period_start', 'period_end')},
            },
        ),
    ]
