# Generated by Django 5.0.2 on 2025-08-24 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidgetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(db_index=True, max_length=100)),
                ('widgets', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widget_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration des widgets du tableau de bord',
                'verbose_name_plural': 'Configurations des widgets du tableau de bord',
                'indexes': [models.Index(fields=['role'], name='dashboard_d_role_73f17e_idx'), models.Index(fields=['user'], name='dashboard_d_user_id_589c59_idx')],
                'unique_together': {('role', 'user')},
            },
        ),
    ]
