# Generated by Django 5.0.2 on 2025-10-01 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dashboardwidgetconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dashboardwidgetconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('role',), name='uniq_dashboard_role_global'),
        ),
        migrations.AddConstraint(
            model_name='dashboardwidgetconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user',), name='uniq_dashboard_user_override'),
        ),
    ]
