# Catalogue complet des widgets disponibles
# Source unique de vérité pour le frontend et backend
AVAILABLE_WIDGETS = {
  # ==================== PROJETS ====================
  'projects.status_distribution': {
    'key': 'projects.status_distribution',
    'label': 'Répartition des Statuts',
    'description': 'Distribution des projets par statut (Prospection, Production, etc.)',
    'type': 'projects',
    'category': 'basic',
    'defaultEnabled': True,
    'availableFor': ['all'],
  },
  'projects.total_projects': {
    'key': 'projects.total_projects',
    'label': 'Total des Projets',
    'description': 'Nombre total de projets dans le système',
    'type': 'projects',
    'category': 'kpi',
    'defaultEnabled': True,
    'availableFor': ['all'],
  },
  'projects.active_projects': {
    'key': 'projects.active_projects',
    'label': 'Projets Actifs',
    'description': 'Nombre de projets actuellement actifs',
    'type': 'projects',
    'category': 'kpi',
    'defaultEnabled': True,
    'availableFor': ['all'],
  },
  'projects.recent_projects': {
    'key': 'projects.recent_projects',
    'label': 'Projets Récents',
    'description': 'Liste des projets récemment créés ou modifiés',
    'type': 'projects',
    'category': 'basic',
    'defaultEnabled': True,
    'availableFor': ['all'],
  },
  'projects.overdue_projects': {
    'key': 'projects.overdue_projects',
    'label': 'Projets en Retard',
    'description': 'Projets ayant dépassé leur deadline',
    'type': 'projects',
    'category': 'basic',
    'defaultEnabled': True,
    'availableFor': ['all'],
  },
  'projects.team_performance': {
    'key': 'projects.team_performance',
    'label': 'Performance des Équipes',
    'description': 'Performance et progression par équipe',
    'type': 'projects',
    'category': 'chart',
    'defaultEnabled': True,
    'availableFor': ['admin', 'manager'],
  },
  'projects.monthly_projects': {
    'key': 'projects.monthly_projects',
    'label': 'Projets par Mois',
    'description': 'Évolution du nombre de projets par mois',
    'type': 'projects',
    'category': 'chart',
    'defaultEnabled': True,
    'availableFor': ['admin', 'manager'],
  },
  'projects.project_performance': {
    'key': 'projects.project_performance',
    'label': 'Performance des Projets',
    'description': 'Métriques de performance détaillées par projet',
    'type': 'projects',
    'category': 'advanced',
    'defaultEnabled': False,
    'availableFor': ['admin', 'manager'],
  },

  # ==================== FINANCIER ====================
  'financial.revenue_trend': {
    'key': 'financial.revenue_trend',
    'label': 'Tendance des Revenus',
    'description': 'Évolution des revenus sur la période',
    'type': 'financial',
    'category': 'chart',
    'defaultEnabled': True,
    'availableFor': ['admin', 'manager'],
  },
  'financial.cash_flow': {
    'key': 'financial.cash_flow',
    'label': 'Flux de Trésorerie',
    'description': 'Vue d\'ensemble des entrées et sorties',
    'type': 'financial',
    'category': 'kpi',
    'defaultEnabled': True,
    'availableFor': ['admin', 'manager'],
  },
  'financial.billing_status': {
    'key': 'financial.billing_status',
    'label': 'État de Facturation',
    'description': 'Statut des factures (payées, en attente, en retard)',
    'type': 'financial',
    'category': 'basic',
    'defaultEnabled': True,
    'availableFor': ['admin', 'manager'],
  },
  'financial.total_factures_amount': {
    'key': 'financial.total_factures_amount',
    'label': 'Montant Total Facturé',
    'description': 'Somme totale des factures émises',
    'type': 'financial',
    'category': 'kpi',
    'defaultEnabled': True,
    'availableFor': ['admin', 'manager'],
  },
  'financial.total_paid_amount': {
    'key': 'financial.total_paid_amount',
    'label': 'Montant Payé',
    'description': 'Somme des paiements reçus',
    'type': 'financial',
    'category': 'kpi',
    'defaultEnabled': True,
    'availableFor': ['admin', 'manager'],
  },
  'financial.total_impayees_amount': {
    'key': 'financial.total_impayees_amount',
    'label': 'Montant Impayé',
    'description': 'Montant des factures non payées',
    'type': 'financial',
    'category': 'kpi',
    'defaultEnabled': True,
    'availableFor': ['admin', 'manager'],
  },
  'financial.taux_recouvrement': {
    'key': 'financial.taux_recouvrement',
    'label': 'Taux de Recouvrement',
    'description': 'Pourcentage des factures recouvrées',
    'type': 'financial',
    'category': 'kpi',
    'defaultEnabled': True,
    'availableFor': ['admin', 'manager'],
  },
  'financial.montant_impaye': {
    'key': 'financial.montant_impaye',
    'label': 'Montant Impayé',
    'description': 'Montant total des factures impayées',
    'type': 'financial',
    'category': 'kpi',
    'defaultEnabled': True,
    'availableFor': ['admin', 'manager'],
  },
  'financial.total_en_retard_amount': {
    'key': 'financial.total_en_retard_amount',
    'label': 'Factures en Retard',
    'description': 'Montant des factures en retard',
    'type': 'financial',
    'category': 'kpi',
    'defaultEnabled': True,
    'availableFor': ['admin', 'manager'],
  },
  'financial.facture_non_emises': {
    'key': 'financial.facture_non_emises',
    'label': 'Factures Non Émises',
    'description': 'Montant des factures non encore émises',
    'type': 'financial',
    'category': 'kpi',
    'defaultEnabled': True,
    'availableFor': ['admin', 'manager'],
  },

  # ==================== PERFORMANCE ====================
  'performance.pending_tasks': {
    'key': 'performance.pending_tasks',
    'label': 'Tâches en Attente',
    'description': 'Nombre de tâches à traiter',
    'type': 'performance',
    'category': 'kpi',
    'defaultEnabled': True,
    'availableFor': ['all'],
  },
  'performance.overdue_tasks': {
    'key': 'performance.overdue_tasks',
    'label': 'Tâches en Retard',
    'description': 'Tâches ayant dépassé leur échéance',
    'type': 'performance',
    'category': 'kpi',
    'defaultEnabled': True,
    'availableFor': ['all'],
  },
  'performance.team_productivity': {
    'key': 'performance.team_productivity',
    'label': 'Productivité d\'Équipe',
    'description': 'Métriques de productivité par équipe',
    'type': 'performance',
    'category': 'advanced',
    'defaultEnabled': False,
    'availableFor': ['admin', 'manager'],
  },

  # ==================== CALENDRIER ====================
  'calendar.upcoming_deadlines': {
    'key': 'calendar.upcoming_deadlines',
    'label': 'Échéances à Venir',
    'description': 'Deadlines des projets à venir',
    'type': 'calendar',
    'category': 'basic',
    'defaultEnabled': True,
    'availableFor': ['all'],
  },
  'calendar.resource_utilization': {
    'key': 'calendar.resource_utilization',
    'label': 'Utilisation des Ressources',
    'description': 'Taux d\'utilisation des ressources',
    'type': 'calendar',
    'category': 'advanced',
    'defaultEnabled': False,
    'availableFor': ['admin', 'manager'],
  },

  # ==================== WIDGETS AVANCÉS ====================
  'advanced.kpis': {
    'key': 'advanced.kpis',
    'label': 'KPIs Avancés',
    'description': 'Indicateurs de performance avancés (ROI, Vélocité, Burn Rate, etc.)',
    'type': 'analytics',
    'category': 'kpi',
    'defaultEnabled': False,
    'availableFor': ['admin', 'manager'],
  },
  'advanced.interactive_charts': {
    'key': 'advanced.interactive_charts',
    'label': 'Graphiques Interactifs',
    'description': 'Graphiques Recharts avec interactions avancées',
    'type': 'analytics',
    'category': 'chart',
    'defaultEnabled': False,
    'availableFor': ['admin', 'manager'],
  },
  'advanced.period_comparison': {
    'key': 'advanced.period_comparison',
    'label': 'Comparaison de Périodes',
    'description': 'Analyse comparative entre deux périodes',
    'type': 'analytics',
    'category': 'analysis',
    'defaultEnabled': False,
    'availableFor': ['admin', 'manager'],
  },
  'advanced.forecasting': {
    'key': 'advanced.forecasting',
    'label': 'Prévisions',
    'description': 'Prévisions financières avec 3 méthodes (linéaire, moyenne mobile, exponentiel)',
    'type': 'analytics',
    'category': 'analysis',
    'defaultEnabled': False,
    'dependsOn': ['financial.revenue_trend'],
    'availableFor': ['admin', 'manager'],
  },
  'advanced.data_export': {
    'key': 'advanced.data_export',
    'label': 'Export de Données',
    'description': 'Export multi-formats (Excel, CSV, PDF, PNG)',
    'type': 'analytics',
    'category': 'advanced',
    'defaultEnabled': False,
    'availableFor': ['admin', 'manager'],
  },
  'advanced.interactive_table': {
    'key': 'advanced.interactive_table',
    'label': 'Tableau Interactif',
    'description': 'Tableau avec tri, recherche et pagination avancée',
    'type': 'analytics',
    'category': 'table',
    'defaultEnabled': False,
    'availableFor': ['admin', 'manager'],
  },
  'advanced.heatmap': {
    'key': 'advanced.heatmap',
    'label': 'Carte de Chaleur',
    'description': 'Heatmap d\'activité (7 jours × 24 heures)',
    'type': 'analytics',
    'category': 'chart',
    'defaultEnabled': False,
    'availableFor': ['admin', 'manager'],
  },
  'advanced.funnel': {
    'key': 'advanced.funnel',
    'label': 'Entonnoir de Conversion',
    'description': 'Funnel chart montrant le parcours de conversion',
    'type': 'analytics',
    'category': 'chart',
    'defaultEnabled': False,
    'availableFor': ['admin', 'manager'],
  },
  'advanced.filters': {
    'key': 'advanced.filters',
    'label': 'Filtres Avancés',
    'description': 'Système de filtrage multi-critères',
    'type': 'analytics',
    'category': 'advanced',
    'defaultEnabled': False,
    'availableFor': ['admin', 'manager'],
  },

  # ==================== ALERTES ====================
  'alerts.urgent_deadlines': {
    'key': 'alerts.urgent_deadlines',
    'label': 'Échéances Urgentes',
    'description': 'Alertes pour les échéances dans les 3 prochains jours',
    'type': 'alerts',
    'category': 'basic',
    'defaultEnabled': True,
    'dependsOn': ['calendar.upcoming_deadlines'],
    'availableFor': ['all'],
  },
  'alerts.overdue_alerts': {
    'key': 'alerts.overdue_alerts',
    'label': 'Alertes de Retard',
    'description': 'Notifications pour les projets et tâches en retard',
    'type': 'alerts',
    'category': 'basic',
    'defaultEnabled': True,
    'dependsOn': ['projects.overdue_projects'],
    'availableFor': ['all'],
  },
}

# Groupes de widgets pour l'organisation
WIDGET_GROUPS = {
  'projects': {
    'label': 'Projets',
    'icon': 'Target',
    'widgets': [
      'projects.total_projects',
      'projects.active_projects',
      'projects.status_distribution',
      'projects.recent_projects',
      'projects.overdue_projects',
      'projects.team_performance',
      'projects.monthly_projects',
      'projects.project_performance',
    ],
  },
  'financial': {
    'label': 'Financier',
    'icon': 'DollarSign',
    'widgets': [
      'financial.revenue_trend',
      'financial.cash_flow',
      'financial.billing_status',
      'financial.total_factures_amount',
      'financial.total_paid_amount',
      'financial.total_impayees_amount',
      'financial.taux_recouvrement',
      'financial.montant_impaye',
      'financial.total_en_retard_amount',
      'financial.facture_non_emises',
    ],
  },
  'performance': {
    'label': 'Performance',
    'icon': 'Users',
    'widgets': [
      'performance.pending_tasks',
      'performance.overdue_tasks',
      'performance.team_productivity',
    ],
  },
  'calendar': {
    'label': 'Calendrier',
    'icon': 'Calendar',
    'widgets': [
      'calendar.upcoming_deadlines',
      'calendar.resource_utilization',
    ],
  },
  'analytics': {
    'label': 'Analyses Avancées',
    'icon': 'TrendingUp',
    'widgets': [
      'advanced.kpis',
      'advanced.interactive_charts',
      'advanced.period_comparison',
      'advanced.forecasting',
      'advanced.data_export',
      'advanced.interactive_table',
      'advanced.heatmap',
      'advanced.funnel',
      'advanced.filters',
    ],
  },
  'alerts': {
    'label': 'Alertes',
    'icon': 'AlertTriangle',
    'widgets': [
      'alerts.urgent_deadlines',
      'alerts.overdue_alerts',
    ],
  },
}

# Présets de configuration par rôle
ROLE_PRESETS = {
  'Managing Director': [
    'advanced.kpis',
    'advanced.interactive_charts',
    'advanced.period_comparison',
    'advanced.forecasting',
    'financial.revenue_trend',
    'financial.cash_flow',
    'financial.total_factures_amount',
    'financial.taux_recouvrement',
    'financial.montant_impaye',
    'financial.total_en_retard_amount',
    'financial.facture_non_emises',
    'projects.status_distribution',
    'projects.total_projects',
    'projects.team_performance',
    'advanced.data_export',
  ],
  'Finance/Admin': [
    'financial.revenue_trend',
    'financial.cash_flow',
    'financial.billing_status',
    'financial.total_factures_amount',
    'financial.total_paid_amount',
    'financial.total_impayees_amount',
    'financial.taux_recouvrement',
    'financial.montant_impaye',
    'financial.total_en_retard_amount',
    'financial.facture_non_emises',
    'advanced.forecasting',
    'advanced.interactive_charts',
    'advanced.data_export',
  ],
  'Chef de projet': [
    'projects.total_projects',
    'projects.active_projects',
    'projects.status_distribution',
    'projects.recent_projects',
    'projects.overdue_projects',
    'projects.team_performance',
    'performance.pending_tasks',
    'performance.overdue_tasks',
    'calendar.upcoming_deadlines',
    'alerts.urgent_deadlines',
    'alerts.overdue_alerts',
  ],
  'Designer': [
    'projects.active_projects',
    'projects.status_distribution',
    'performance.pending_tasks',
    'calendar.upcoming_deadlines',
  ],
  'Développeur': [
    'projects.active_projects',
    'projects.status_distribution',
    'performance.pending_tasks',
    'performance.overdue_tasks',
    'calendar.upcoming_deadlines',
  ],
  'Rédacteur': [
    'projects.active_projects',
    'performance.pending_tasks',
    'calendar.upcoming_deadlines',
  ],
  'Consultant': [
    'projects.status_distribution',
    'projects.team_performance',
    'performance.team_productivity',
  ],
}