# Generated by Django 5.0.2 on 2025-06-21 19:44

import django.core.validators
import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=documents.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'jpg', 'jpeg', 'png', 'gif', 'mp4', 'avi', 'mp3', 'zip'])])),
                ('document_type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Document Word'), ('docx', 'Document Word'), ('xls', 'Feuille de calcul Excel'), ('xlsx', 'Feuille de calcul Excel'), ('ppt', 'Présentation PowerPoint'), ('pptx', 'Présentation PowerPoint'), ('txt', 'Fichier texte'), ('jpg', 'Image JPEG'), ('jpeg', 'Image JPEG'), ('png', 'Image PNG'), ('gif', 'Image GIF'), ('mp4', 'Vidéo MP4'), ('avi', 'Vidéo AVI'), ('mp3', 'Audio MP3'), ('zip', 'Archive ZIP'), ('other', 'Autre')], max_length=10)),
                ('category', models.CharField(choices=[('contract', 'Contrat'), ('proposal', 'Proposition'), ('report', 'Rapport'), ('presentation', 'Présentation'), ('design', 'Design'), ('video', 'Vidéo'), ('audio', 'Audio'), ('photo', 'Photo'), ('other', 'Autre')], default='other', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('file_size', models.BigIntegerField(help_text='Taille du fichier en bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='documents.document')),
            ],
            options={
                'verbose_name': 'Commentaire de document',
                'verbose_name_plural': 'Commentaires de document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=documents.models.document_upload_path)),
                ('version_number', models.PositiveIntegerField()),
                ('changes_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Version de document',
                'verbose_name_plural': 'Versions de document',
                'ordering': ['-version_number'],
                'unique_together': {('document', 'version_number')},
            },
        ),
    ]
