# Generated by Django 5.0.2 on 2025-07-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0002_contrat_echeances_contrat'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='fichier_signe',
            field=models.FileField(blank=True, null=True, upload_to='contrats/signes/'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('actif', 'Actif'), ('termine', 'Terminé'), ('annule', 'Annulé'), ('suspendu', 'Suspendu'), ('archive', 'Archivé'), ('envoye', 'Envoyé')], default='brouillon', max_length=20),
        ),
    ]
