# Generated by Django 5.0.2 on 2025-07-30 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0004_alter_contrat_statut_avenant'),
        ('devis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='devis_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrat_principal', to='devis.devis', verbose_name='Devis principal'),
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='devis',
        ),
        migrations.AddField(
            model_name='contrat',
            name='devis',
            field=models.ManyToManyField(blank=True, related_name='contrats', to='devis.devis', verbose_name='Devis associés'),
        ),
    ]
