# Generated by Django 5.0.2 on 2025-07-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0005_contrat_devis_principal_remove_contrat_devis_and_more'),
        ('devis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='devis',
            field=models.ManyToManyField(blank=True, null=True, related_name='contrats', to='devis.devis', verbose_name='Devis associés'),
        ),
    ]
