# Generated by Django 5.0.2 on 2025-12-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0007_contrathistoriquemontant'),
    ]

    operations = [
        migrations.AddField(
            model_name='echeanciercontrat',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Informations comme version, type (initial/extension), etc.', verbose_name="Métadonnées de l'échéance"),
        ),
    ]
