# Generated by Django 5.0.2 on 2025-12-11 22:46

from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0008_echeanciercontrat_metadata'),
    ]

    operations = [
        # Step 1: Rename the old EcheancierContrat model to EcheancierContratOld
        # Using SeparateDatabaseAndState to only update migration state without touching the database
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameModel(
                    old_name='EcheancierContrat',
                    new_name='EcheancierContratOld',
                ),
                migrations.AlterField(
                    model_name='echeanciercontratold',
                    name='contrat',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances_old', to='contrats.contrat'),
                ),
                migrations.AlterModelOptions(
                    name='echeanciercontratold',
                    options={
                        'ordering': ['contrat', 'numero_echeance'],
                        'verbose_name': 'Échéance de contrat (ancien modèle)',
                        'verbose_name_plural': 'Échéances de contrat (ancien modèle)',
                    },
                ),
                migrations.AlterModelTable(
                    name='echeanciercontratold',
                    table='contrats_echeanciercontrat',
                ),
            ],
            database_operations=[
                # No database operations - the table stays as-is
            ],
        ),

        # Step 5: Create the new EcheancierContrat model (header)
        migrations.CreateModel(
            name='EcheancierContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_echeancier', models.CharField(
                    max_length=20,
                    choices=[
                        ('initial', 'Échéancier initial'),
                        ('extension', 'Extension de contrat'),
                        ('avenant', 'Suite à avenant'),
                        ('modification', 'Modification'),
                    ],
                    default='initial'
                )),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict, blank=True)),
                ('contrat', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='echeanciers',
                    to='contrats.contrat'
                )),
            ],
            options={
                'db_table': 'contrats_echeancier',
                'verbose_name': 'Échéancier de contrat',
                'verbose_name_plural': 'Échéanciers de contrat',
                'ordering': ['contrat', '-date_creation'],
            },
        ),

        # Step 6: Create the new LigneEcheancierContrat model
        migrations.CreateModel(
            name='LigneEcheancierContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_echeance', models.PositiveIntegerField(help_text="Numéro de l'échéance (1, 2, 3, etc.)")),
                ('type_echeance', models.CharField(
                    max_length=20,
                    choices=[
                        ('acompte', 'Acompte'),
                        ('tranche', 'Tranche de paiement'),
                        ('solde', 'Solde'),
                        ('retention', 'Retenue de garantie'),
                    ],
                    default='tranche'
                )),
                ('montant_ht', models.DecimalField(max_digits=12, decimal_places=2, validators=[django.core.validators.MinValueValidator(0)])),
                ('montant_tva', models.DecimalField(max_digits=12, decimal_places=2, default=0)),
                ('montant_ttc', models.DecimalField(max_digits=12, decimal_places=2, validators=[django.core.validators.MinValueValidator(0)])),
                ('pourcentage', models.DecimalField(
                    max_digits=5,
                    decimal_places=2,
                    validators=[django.core.validators.MinValueValidator(0)],
                    default=0,
                    help_text="Pourcentage du montant total du contrat"
                )),
                ('date_echeance', models.DateField()),
                ('date_paiement', models.DateField(null=True, blank=True)),
                ('statut', models.CharField(
                    max_length=20,
                    choices=[
                        ('en_attente', 'En attente'),
                        ('paye', 'Payé'),
                        ('en_retard', 'En retard'),
                        ('annule', 'Annulé'),
                    ],
                    default='en_attente'
                )),
                ('commentaire', models.TextField(blank=True)),
                ('alerte_envoyee', models.BooleanField(default=False, help_text="Alerte envoyée 3 jours avant l'échéance")),
                ('metadata', models.JSONField(default=dict, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('echeancier', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='lignes',
                    to='contrats.echeanciercontrat'
                )),
            ],
            options={
                'verbose_name': "Ligne d'échéancier de contrat",
                'verbose_name_plural': "Lignes d'échéancier de contrat",
                'ordering': ['echeancier', 'numero_echeance'],
            },
        ),
    ]
