# Generated by Django 5.0.2 on 2026-01-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0013_lignecontrat_commentaire_retrait_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrathistoriquemontant',
            name='type_modification',
            field=models.CharField(choices=[('ajout_devis', 'Ajout de devis'), ('suppression_devis', 'Suppression de devis'), ('modification_ligne', 'Modification de ligne'), ('retrait_ligne', 'Retrait de ligne'), ('avenant', 'Avenant'), ('recalcul', 'Recalcul')], max_length=50),
        ),
    ]
