# Generated by Django 5.0.2 on 2026-01-09 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0014_alter_contrathistoriquemontant_type_modification'),
        ('devis', '0005_lignedevis_commentaire_retrait_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecontrat',
            name='ligne_devis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes_contrat', to='devis.lignedevis'),
        ),
    ]
