# Generated by Django 5.0.2 on 2025-07-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='adresse_complete',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='raison_sociale',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='rccm_nif',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='statut_commercial',
            field=models.CharField(choices=[('prospect', 'Prospect'), ('actif', 'Actif'), ('inactif', 'Inactif'), ('bloque', 'Bloqué')], default='prospect', max_length=20),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='type_client',
            field=models.CharField(choices=[('personne_physique', 'Personne physique'), ('personne_morale', 'Personne morale')], default='personne_physique', max_length=20),
        ),
    ]
