# Generated by Django 5.0.2 on 2025-09-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_date_format_userprofile_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='comment_mentions',
            field=models.BooleanField(default=True, help_text='Notifications quand vous êtes mentionné dans un commentaire'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deadline_reminders',
            field=models.BooleanField(default=True, help_text="Rappels pour les activités en approche d'échéance"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='document_sharing',
            field=models.BooleanField(default=True, help_text='Notifications quand un document est partagé avec vous'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Recevoir les notifications par email'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='invoice_reminders',
            field=models.BooleanField(default=True, help_text='Rappels pour les factures en attente de paiement'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='project_updates',
            field=models.BooleanField(default=True, help_text='Notifications sur les changements de statut des projets'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='push_notifications',
            field=models.BooleanField(default=True, help_text='Recevoir les notifications push dans le navigateur'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='task_assignments',
            field=models.BooleanField(default=True, help_text="Notifications lors de l'attribution de nouvelles tâches"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='team_messages',
            field=models.BooleanField(default=True, help_text="Notifications sur les nouveaux messages d'équipe"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weekly_reports',
            field=models.BooleanField(default=False, help_text="Recevoir un résumé hebdomadaire de l'activité"),
        ),
    ]
