# Generated by Django 5.0.2 on 2025-07-21 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_clientcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.clientcategory', verbose_name='Catégorie'),
        ),
    ]
