# Generated by Django 5.0.2 on 2025-07-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_clientprofile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='prenom',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
